[2025-03-17T20:00:42.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:00:42.645+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:00:42.906+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:00:42.926+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:00:43.255+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.events_project_b_db> on 2025-03-17 19:50:00+00:00
[2025-03-17T20:00:43.486+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.events_project_b_db', 'scheduled__2025-03-17T19:50:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmptrg21iz5']
[2025-03-17T20:00:43.534+0000] {standard_task_runner.py:105} INFO - Job 227: Subtask load_tables.events_project_b_db
[2025-03-17T20:00:43.506+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:00:43.575+0000] {standard_task_runner.py:72} INFO - Started process 3280 to run task
[2025-03-17T20:00:46.302+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T19:50:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:00:49.273+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.events_project_b_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T19:50:00+00:00'
[2025-03-17T20:00:49.422+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:00:50.052+0000] {sql.py:278} INFO - Executing: select load_tables('events_project_b_db', 'events');
[2025-03-17T20:00:50.363+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:00:51.281+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:00:51.742+0000] {sql.py:553} INFO - Running statement: select load_tables('events_project_b_db', 'events');, parameters: None
[2025-03-17T20:00:55.562+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:00:56.223+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:00:56.273+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.events_project_b_db, run_id=scheduled__2025-03-17T19:50:00+00:00, execution_date=20250317T195000, start_date=20250317T200042, end_date=20250317T200056
[2025-03-17T20:00:57.381+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:00:57.971+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:00:58.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
