[2025-03-17T20:10:14.223+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:10:14.734+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T20:00:00+00:00 [queued]>
[2025-03-17T20:10:15.225+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T20:00:00+00:00 [queued]>
[2025-03-17T20:10:15.283+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:10:15.634+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.events_project_b_db> on 2025-03-17 20:00:00+00:00
[2025-03-17T20:10:15.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3413) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:10:16.134+0000] {standard_task_runner.py:72} INFO - Started process 3422 to run task
[2025-03-17T20:10:16.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.events_project_b_db', 'scheduled__2025-03-17T20:00:00+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmppwtu447s']
[2025-03-17T20:10:16.206+0000] {standard_task_runner.py:105} INFO - Job 240: Subtask load_tables.events_project_b_db
[2025-03-17T20:10:18.707+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.events_project_b_db scheduled__2025-03-17T20:00:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:10:21.366+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.events_project_b_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:00:00+00:00'
[2025-03-17T20:10:21.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:10:21.656+0000] {sql.py:278} INFO - Executing: select load_tables('events_project_b_db', 'events');
[2025-03-17T20:10:21.967+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:10:22.166+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:10:22.245+0000] {sql.py:553} INFO - Running statement: select load_tables('events_project_b_db', 'events');, parameters: None
[2025-03-17T20:10:22.516+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:10:23.047+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:10:23.076+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.events_project_b_db, run_id=scheduled__2025-03-17T20:00:00+00:00, execution_date=20250317T200000, start_date=20250317T201014, end_date=20250317T201023
[2025-03-17T20:10:23.376+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:10:23.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
