[2025-03-17T19:50:20.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T19:50:20.158+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:40:00+00:00 [queued]>
[2025-03-17T19:50:20.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:40:00+00:00 [queued]>
[2025-03-17T19:50:20.287+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T19:50:20.578+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_analytics_sessions> on 2025-03-17 19:40:00+00:00
[2025-03-17T19:50:20.798+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T19:50:20.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_analytics_sessions', 'scheduled__2025-03-17T19:40:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpfrw8xfew']
[2025-03-17T19:50:20.846+0000] {standard_task_runner.py:72} INFO - Started process 3159 to run task
[2025-03-17T19:50:20.856+0000] {standard_task_runner.py:105} INFO - Job 225: Subtask load_analytics_sessions
[2025-03-17T19:50:21.219+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:40:00+00:00 [running]> on host c032966e105e
[2025-03-17T19:50:21.799+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_analytics_sessions' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T19:40:00+00:00'
[2025-03-17T19:50:21.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T19:50:21.879+0000] {sql.py:278} INFO - Executing: select load_analytics_sessions();
[2025-03-17T19:50:21.919+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:50:21.987+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:50:21.999+0000] {sql.py:553} INFO - Running statement: select load_analytics_sessions();, parameters: None
[2025-03-17T19:50:22.096+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T19:50:22.219+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T19:50:22.228+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_analytics_sessions, run_id=scheduled__2025-03-17T19:40:00+00:00, execution_date=20250317T194000, start_date=20250317T195020, end_date=20250317T195022
[2025-03-17T19:50:22.337+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T19:50:22.387+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
