[2025-03-17T20:00:43.096+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:00:44.275+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.pages_project_b_db scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:00:45.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.pages_project_b_db scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:00:45.295+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:00:45.895+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.pages_project_b_db> on 2025-03-17 19:50:00+00:00
[2025-03-17T20:00:46.173+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:00:46.212+0000] {standard_task_runner.py:72} INFO - Started process 3288 to run task
[2025-03-17T20:00:46.261+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.pages_project_b_db', 'scheduled__2025-03-17T19:50:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpl_ykbb1u']
[2025-03-17T20:00:46.281+0000] {standard_task_runner.py:105} INFO - Job 232: Subtask load_tables.pages_project_b_db
[2025-03-17T20:00:47.803+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.pages_project_b_db scheduled__2025-03-17T19:50:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:00:50.381+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.pages_project_b_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T19:50:00+00:00'
[2025-03-17T20:00:50.392+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:00:50.763+0000] {sql.py:278} INFO - Executing: select load_tables('pages_project_b_db', 'pages');
[2025-03-17T20:00:51.122+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:00:51.913+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:00:52.433+0000] {sql.py:553} INFO - Running statement: select load_tables('pages_project_b_db', 'pages');, parameters: None
[2025-03-17T20:00:52.611+0000] {job.py:229} INFO - Heartbeat recovered after 11.12 seconds
[2025-03-17T20:00:54.551+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:00:55.243+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:00:55.251+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.pages_project_b_db, run_id=scheduled__2025-03-17T19:50:00+00:00, execution_date=20250317T195000, start_date=20250317T200044, end_date=20250317T200055
[2025-03-17T20:00:56.173+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:00:56.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-17T20:00:56.951+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
